// This file is generated by FluentCodegen
// It does not make sense to change something here
// No stress :)
using System;
namespace Xamarin.Forms.Fluent
{
    public static partial class RelativeLayoutExtensions
    {

        
        public static TBindable BindXConstraintRelativeLayout<TBindable>(this TBindable self,
            string path,
            BindingMode mode = BindingMode.Default,
            IValueConverter converter = null,
            object converterParameter = null,
            string stringFormat = null,
            object source = null,
            object targetNullValue = null,
            object fallbackValue = null) where TBindable : RelativeLayout
                => self.Bind(RelativeLayout.XConstraintProperty, path, mode, converter, converterParameter, stringFormat, source, targetNullValue, fallbackValue);
        
        public static TBindable SetXConstraint<TBindable>(this TBindable bindable, Constraint value) where TBindable : BindableObject
            => bindable.Set(RelativeLayout.XConstraintProperty, value);
        
        public static TBindable BindYConstraintRelativeLayout<TBindable>(this TBindable self,
            string path,
            BindingMode mode = BindingMode.Default,
            IValueConverter converter = null,
            object converterParameter = null,
            string stringFormat = null,
            object source = null,
            object targetNullValue = null,
            object fallbackValue = null) where TBindable : RelativeLayout
                => self.Bind(RelativeLayout.YConstraintProperty, path, mode, converter, converterParameter, stringFormat, source, targetNullValue, fallbackValue);
        
        public static TBindable SetYConstraint<TBindable>(this TBindable bindable, Constraint value) where TBindable : BindableObject
            => bindable.Set(RelativeLayout.YConstraintProperty, value);
        
        public static TBindable BindWidthConstraintRelativeLayout<TBindable>(this TBindable self,
            string path,
            BindingMode mode = BindingMode.Default,
            IValueConverter converter = null,
            object converterParameter = null,
            string stringFormat = null,
            object source = null,
            object targetNullValue = null,
            object fallbackValue = null) where TBindable : RelativeLayout
                => self.Bind(RelativeLayout.WidthConstraintProperty, path, mode, converter, converterParameter, stringFormat, source, targetNullValue, fallbackValue);
        
        public static TBindable SetWidthConstraint<TBindable>(this TBindable bindable, Constraint value) where TBindable : BindableObject
            => bindable.Set(RelativeLayout.WidthConstraintProperty, value);
        
        public static TBindable BindHeightConstraintRelativeLayout<TBindable>(this TBindable self,
            string path,
            BindingMode mode = BindingMode.Default,
            IValueConverter converter = null,
            object converterParameter = null,
            string stringFormat = null,
            object source = null,
            object targetNullValue = null,
            object fallbackValue = null) where TBindable : RelativeLayout
                => self.Bind(RelativeLayout.HeightConstraintProperty, path, mode, converter, converterParameter, stringFormat, source, targetNullValue, fallbackValue);
        
        public static TBindable SetHeightConstraint<TBindable>(this TBindable bindable, Constraint value) where TBindable : BindableObject
            => bindable.Set(RelativeLayout.HeightConstraintProperty, value);
        
        public static TBindable BindBoundsConstraintRelativeLayout<TBindable>(this TBindable self,
            string path,
            BindingMode mode = BindingMode.Default,
            IValueConverter converter = null,
            object converterParameter = null,
            string stringFormat = null,
            object source = null,
            object targetNullValue = null,
            object fallbackValue = null) where TBindable : RelativeLayout
                => self.Bind(RelativeLayout.BoundsConstraintProperty, path, mode, converter, converterParameter, stringFormat, source, targetNullValue, fallbackValue);
        
        public static TBindable SetBoundsConstraint<TBindable>(this TBindable bindable, BoundsConstraint value) where TBindable : BindableObject
            => bindable.Set(RelativeLayout.BoundsConstraintProperty, value);
    }
}