// This file is generated by FluentCodegen
// It does not make sense to change something here
// No stress :)
using System;
namespace Xamarin.Forms.Fluent
{
    public static partial class WebViewExtensions
    {


        public static TBindable WithNavigatedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.WebNavigatedEventArgs> handlerAction) where TBindable : WebView
        {
            self.Navigated += handlerAction;

            return self;
        }

        public static TBindable ClearNavigatedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "Navigated");

            return self;
        }

        public static TBindable WithNavigatingEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.WebNavigatingEventArgs> handlerAction) where TBindable : WebView
        {
            self.Navigating += handlerAction;

            return self;
        }

        public static TBindable ClearNavigatingEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "Navigating");

            return self;
        }

        public static TBindable WithEvalRequestedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.Internals.EvalRequested> handlerAction) where TBindable : WebView
        {
            self.EvalRequested += handlerAction;

            return self;
        }

        public static TBindable ClearEvalRequestedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "EvalRequested");

            return self;
        }

        public static TBindable WithEvaluateJavaScriptRequestedEvent<TBindable>(this TBindable self,
            Xamarin.Forms.Internals.EvaluateJavaScriptDelegate handlerAction) where TBindable : WebView
        {
            self.EvaluateJavaScriptRequested += handlerAction;

            return self;
        }

        public static TBindable ClearEvaluateJavaScriptRequestedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "EvaluateJavaScriptRequested");

            return self;
        }

        public static TBindable WithGoBackRequestedEvent<TBindable>(this TBindable self,
            System.EventHandler handlerAction) where TBindable : WebView
        {
            self.GoBackRequested += handlerAction;

            return self;
        }

        public static TBindable ClearGoBackRequestedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "GoBackRequested");

            return self;
        }

        public static TBindable WithGoForwardRequestedEvent<TBindable>(this TBindable self,
            System.EventHandler handlerAction) where TBindable : WebView
        {
            self.GoForwardRequested += handlerAction;

            return self;
        }

        public static TBindable ClearGoForwardRequestedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "GoForwardRequested");

            return self;
        }

        public static TBindable WithChildrenReorderedEvent<TBindable>(this TBindable self,
            System.EventHandler handlerAction) where TBindable : WebView
        {
            self.ChildrenReordered += handlerAction;

            return self;
        }

        public static TBindable ClearChildrenReorderedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "ChildrenReordered");

            return self;
        }

        public static TBindable WithFocusedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.FocusEventArgs> handlerAction) where TBindable : WebView
        {
            self.Focused += handlerAction;

            return self;
        }

        public static TBindable ClearFocusedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "Focused");

            return self;
        }

        public static TBindable WithMeasureInvalidatedEvent<TBindable>(this TBindable self,
            System.EventHandler handlerAction) where TBindable : WebView
        {
            self.MeasureInvalidated += handlerAction;

            return self;
        }

        public static TBindable ClearMeasureInvalidatedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "MeasureInvalidated");

            return self;
        }

        public static TBindable WithSizeChangedEvent<TBindable>(this TBindable self,
            System.EventHandler handlerAction) where TBindable : WebView
        {
            self.SizeChanged += handlerAction;

            return self;
        }

        public static TBindable ClearSizeChangedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "SizeChanged");

            return self;
        }

        public static TBindable WithUnfocusedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.FocusEventArgs> handlerAction) where TBindable : WebView
        {
            self.Unfocused += handlerAction;

            return self;
        }

        public static TBindable ClearUnfocusedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "Unfocused");

            return self;
        }

        public static TBindable WithBatchCommittedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.Internals.EventArg<Xamarin.Forms.VisualElement>> handlerAction) where TBindable : WebView
        {
            self.BatchCommitted += handlerAction;

            return self;
        }

        public static TBindable ClearBatchCommittedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "BatchCommitted");

            return self;
        }

        public static TBindable WithFocusChangeRequestedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.VisualElement.FocusRequestArgs> handlerAction) where TBindable : WebView
        {
            self.FocusChangeRequested += handlerAction;

            return self;
        }

        public static TBindable ClearFocusChangeRequestedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "FocusChangeRequested");

            return self;
        }

        public static TBindable WithChildAddedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.ElementEventArgs> handlerAction) where TBindable : WebView
        {
            self.ChildAdded += handlerAction;

            return self;
        }

        public static TBindable ClearChildAddedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "ChildAdded");

            return self;
        }

        public static TBindable WithChildRemovedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.ElementEventArgs> handlerAction) where TBindable : WebView
        {
            self.ChildRemoved += handlerAction;

            return self;
        }

        public static TBindable ClearChildRemovedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "ChildRemoved");

            return self;
        }

        public static TBindable WithDescendantAddedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.ElementEventArgs> handlerAction) where TBindable : WebView
        {
            self.DescendantAdded += handlerAction;

            return self;
        }

        public static TBindable ClearDescendantAddedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "DescendantAdded");

            return self;
        }

        public static TBindable WithDescendantRemovedEvent<TBindable>(this TBindable self,
            System.EventHandler<Xamarin.Forms.ElementEventArgs> handlerAction) where TBindable : WebView
        {
            self.DescendantRemoved += handlerAction;

            return self;
        }

        public static TBindable ClearDescendantRemovedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "DescendantRemoved");

            return self;
        }

        public static TBindable WithPlatformSetEvent<TBindable>(this TBindable self,
            System.EventHandler handlerAction) where TBindable : WebView
        {
            self.PlatformSet += handlerAction;

            return self;
        }

        public static TBindable ClearPlatformSetEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "PlatformSet");

            return self;
        }

        public static TBindable WithPropertyChangedEvent<TBindable>(this TBindable self,
            System.ComponentModel.PropertyChangedEventHandler handlerAction) where TBindable : WebView
        {
            self.PropertyChanged += handlerAction;

            return self;
        }

        public static TBindable ClearPropertyChangedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "PropertyChanged");

            return self;
        }

        public static TBindable WithBindingContextChangedEvent<TBindable>(this TBindable self,
            System.EventHandler handlerAction) where TBindable : WebView
        {
            self.BindingContextChanged += handlerAction;

            return self;
        }

        public static TBindable ClearBindingContextChangedEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "BindingContextChanged");

            return self;
        }

        public static TBindable WithPropertyChangingEvent<TBindable>(this TBindable self,
            Xamarin.Forms.PropertyChangingEventHandler handlerAction) where TBindable : WebView
        {
            self.PropertyChanging += handlerAction;

            return self;
        }

        public static TBindable ClearPropertyChangingEventHandlers<TBindable>(this TBindable self) where TBindable : WebView
        {
            Xamarin.Forms.Fluent.EventExtensions.ClearEventInvocations(self, "PropertyChanging");

            return self;
        }
        
        public static TBindable BindSourceWebView<TBindable>(this TBindable self,
            string path,
            BindingMode mode = BindingMode.Default,
            IValueConverter converter = null,
            object converterParameter = null,
            string stringFormat = null,
            object source = null,
            object targetNullValue = null,
            object fallbackValue = null) where TBindable : WebView
                => self.Bind(WebView.SourceProperty, path, mode, converter, converterParameter, stringFormat, source, targetNullValue, fallbackValue);
        
        public static TBindable BindCanGoBackWebView<TBindable>(this TBindable self,
            string path,
            BindingMode mode = BindingMode.Default,
            IValueConverter converter = null,
            object converterParameter = null,
            string stringFormat = null,
            object source = null,
            object targetNullValue = null,
            object fallbackValue = null) where TBindable : WebView
                => self.Bind(WebView.CanGoBackProperty, path, mode, converter, converterParameter, stringFormat, source, targetNullValue, fallbackValue);
        
        public static TBindable BindCanGoForwardWebView<TBindable>(this TBindable self,
            string path,
            BindingMode mode = BindingMode.Default,
            IValueConverter converter = null,
            object converterParameter = null,
            string stringFormat = null,
            object source = null,
            object targetNullValue = null,
            object fallbackValue = null) where TBindable : WebView
                => self.Bind(WebView.CanGoForwardProperty, path, mode, converter, converterParameter, stringFormat, source, targetNullValue, fallbackValue);
    }
}